//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberOpenIds
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string OpenId { get; set; }
        public string UnionOpenId { get; set; }
        public string UnionId { get; set; }
        public string ServiceProvider { get; set; }
        public Nullable<int> AppIdType { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
