//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    public partial class RolePrivileges : BaseModel
    {
        public long Id { get; set; }
        public Nullable<int> Privilege { get; set; }
        public Nullable<long> RoleId { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
